function [N,dNdPsi,dNdEta,dNdTau,IdX] = Shapef_3D(Coor,Degree,NSpE,CaldN,ShapeFType)

if nargin==3
    CaldN=0;
    ShapeFType = 'STD';
    IdX = [];
elseif nargin==4
    ShapeFType = 'STD';
    IdX = [];
elseif ~strcmp(ShapeFType,'Hermite')
    IdX = [];
end

X=Coor(:,1)';
Y=Coor(:,2)';
Z=Coor(:,3)';
Zeros = zeros(1,size(Coor,1));
Ones = ones(1,size(Coor,1));

switch NSpE
    case 4
        switch ShapeFType
            case 'STD'
                switch Degree
                    case 1
                        N = [...
                            Ones - X - Y - Z;...
                            X;...
                            Y;...
                            Z;...
                            ];
                        if CaldN==0
                            dN=0;
                        else
                            dN=[...
                                -Ones, -Ones, -Ones;...
                                Ones,  Zeros, Zeros;...
                                Zeros,  Ones, Zeros;...
                                Zeros, Zeros, Ones];
                        end
                        
                        
                end
            otherwise
                error('Not implemented');
        end
        
    case 6 %Hexahedra
        switch ShapeFType
            case 'STD'
                switch Degree
                    case 1
                        N = [...
                            (1-Y).*(1-X).*(1-Z);...
                            (1-Y).*(1+X).*(1-Z);...
                            (1+Y).*(1+X).*(1-Z);...
                            (1+Y).*(1-X).*(1-Z);...
                            (1-Y).*(1-X).*(1+Z);...
                            (1-Y).*(1+X).*(1+Z);...
                            (1+Y).*(1+X).*(1+Z);...
                            (1+Y).*(1-X).*(1+Z)]/8;
                        if CaldN==0
                            dN=0;
                        else
                            dN=[...
                                -(1-Y).*(1-Z), -(1-X).*(1-Z), -(1-X).*(1-Y);...
                                (1-Y).*(1-Z), -(1+X).*(1-Z), -(1+X).*(1-Y);...
                                (1+Y).*(1-Z),  (1+X).*(1-Z), -(1+X).*(1+Y);...
                                -(1+Y).*(1-Z),  (1-X).*(1-Z), -(1-X).*(1+Y);...
                                -(1-Y).*(1+Z), -(1-X).*(1+Z),  (1-X).*(1-Y);...
                                (1-Y).*(1+Z), -(1+X).*(1+Z),  (1+X).*(1-Y);...
                                (1+Y).*(1+Z),  (1+X).*(1+Z),  (1+X).*(1+Y);...
                                -(1+Y).*(1+Z),  (1-X).*(1+Z),  (1-X).*(1+Y)]/8;
                        end
                    case 2
                        N = [...
                            1/8*(1-X).*(1-Eta).*(1+Tau).*(-X-Eta+Tau-2);...
                            1/8*(1+X).*(1-Eta).*(1+Tau).*(X-Eta+Tau-2);...
                            1/8*(1+X).*(1+Eta).*(1+Tau).*(X+Eta+Tau-2);...
                            1/8*(1-X).*(1+Eta).*(1+Tau).*(-X+Eta+Tau-2);...
                            1/8*(1-X).*(1-Eta).*(1-Tau).*(-X-Eta-Tau-2);...
                            1/8*(1+X).*(1-Eta).*(1-Tau).*(X-Eta-Tau-2);...
                            1/8*(1+X).*(1+Eta).*(1-Tau).*(X+Eta-Tau-2);...
                            1/8*(1-X).*(1+Eta).*(1-Tau).*(-X+Eta-Tau-2);...
                            1/4*(1-X.^2).*(1-Eta).*(1+Tau);...
                            1/4*(1+X).*(1-Eta.^2).*(1+Tau);...
                            1/4*(1-X.^2).*(1+Eta).*(1+Tau);...
                            1/4*(1-X).*(1-Eta.^2).*(1+Tau);...
                            1/4*(1-X).*(1-Eta).*(1-Tau.^2);...
                            1/4*(1+X).*(1-Eta).*(1-Tau.^2);...
                            1/4*(1+X).*(1+Eta).*(1-Tau.^2);...
                            1/4*(1-X).*(1+Eta).*(1-Tau.^2);...
                            1/4*(1-X.^2).*(1-Eta).*(1-Tau);...
                            1/4*(1+X).*(1-Eta.^2).*(1-Tau);...
                            1/4*(1-X.^2).*(1+Eta).*(1-Tau);...
                            1/4*(1-X).*(1-Eta.^2).*(1-Tau)];
                        if CaldN==0
                            dN=0;
                        else
                            dN=[...
                                -((Eta - 1).*(Tau + 1).*(Eta - Tau + 2*Xi + 1))/8, -((Tau + 1).*(Xi - 1).*(2*Eta - Tau + Xi + 1))/8, -((Eta - 1).*(Xi - 1).*(Eta - 2*Tau + Xi + 1))/8;...
                                ((Eta - 1).*(Tau + 1).*(Eta - Tau - 2*Xi + 1))/8, ((Tau + 1).*(Xi + 1).*(2*Eta - Tau - Xi + 1))/8, ((Eta - 1).*(Xi + 1).*(Eta - 2*Tau - Xi + 1))/8;...
                                ((Eta + 1).*(Tau + 1).*(Eta + Tau + 2*Xi - 1))/8, ((Tau + 1).*(Xi + 1).*(2*Eta + Tau + Xi - 1))/8, ((Eta + 1).*(Xi + 1).*(Eta + 2*Tau + Xi - 1))/8;...
                                -((Eta + 1).*(Tau + 1).*(Eta + Tau - 2*Xi - 1))/8, -((Tau + 1).*(Xi - 1).*(2*Eta + Tau - Xi - 1))/8, -((Eta + 1).*(Xi - 1).*(Eta + 2*Tau - Xi - 1))/8;...
                                ((Eta - 1).*(Tau - 1).*(Eta + Tau + 2*Xi + 1))/8, ((Tau - 1).*(Xi - 1).*(2*Eta + Tau + Xi + 1))/8,((Eta - 1).*(Xi - 1).*(Eta + 2*Tau + Xi + 1))/8,...
                                -((Eta - 1).*(Tau - 1).*(Eta + Tau - 2*Xi + 1))/8, -((Tau - 1).*(Xi + 1).*(2*Eta + Tau - Xi + 1))/8, -((Eta - 1).*(Xi + 1).*(Eta + 2*Tau - Xi + 1))/8;...
                                -((Eta + 1).*(Tau - 1).*(Eta - Tau + 2*Xi - 1))/8, -((Tau - 1).*(Xi + 1).*(2*Eta - Tau + Xi - 1))/8, -((Eta + 1).*(Xi + 1).*(Eta - 2*Tau + Xi - 1))/8;...
                                -((Eta + 1).*(Tau - 1).*(Tau - Eta + 2*Xi + 1))/8, -((Tau - 1).*(Xi - 1).*(Tau - 2*Eta + Xi + 1))/8, -((Eta + 1).*(Xi - 1).*(2*Tau - Eta + Xi + 1))/8;...
                                (Xi.*(Eta - 1).*(Tau + 1))/2, (Xi.^2/4 - 1/4).*(Tau + 1), (Xi.^2/4 - 1/4).*(Eta - 1);...
                                -((Eta.^2 - 1).*(Tau + 1))/4, -2*Eta.*(Xi/4 + 1/4).*(Tau + 1), -(Eta.^2 - 1).*(Xi/4 + 1/4);...
                                -(Xi.*(Eta + 1).*(Tau + 1))/2, -(Xi.^2/4 - 1/4).*(Tau + 1), -(Xi.^2/4 - 1/4).*(Eta + 1);...
                                ((Eta.^2 - 1).*(Tau + 1))/4, 2*Eta.*(Xi/4 - 1/4).*(Tau + 1),(Eta.^2 - 1).*(Xi/4 - 1/4);...
                                -((Tau.^2 - 1).*(Eta - 1))/4, -(Tau.^2 - 1).*(Xi/4 - 1/4), -2*Tau.*(Xi/4 - 1/4).*(Eta - 1);...
                                ((Tau.^2 - 1).*(Eta - 1))/4, (Tau.^2 - 1).*(Xi/4 + 1/4), 2*Tau.*(Xi/4 + 1/4).*(Eta - 1);...
                                -((Tau.^2 - 1).*(Eta + 1))/4, -(Tau.^2 - 1).*(Xi/4 + 1/4), -2*Tau.*(Xi/4 + 1/4).*(Eta + 1);...
                                ((Tau.^2 - 1).*(Eta + 1))/4, (Tau.^2 - 1).*(Xi/4 - 1/4), 2*Tau.*(Xi/4 - 1/4).*(Eta + 1);...
                                -(Xi.*(Eta - 1).*(Tau - 1))/2, -(Xi.^2/4 - 1/4).*(Tau - 1), -(Xi.^2/4 - 1/4).*(Eta - 1);...
                                ((Eta.^2 - 1).*(Tau - 1))/4, 2*Eta.*(Xi/4 + 1/4).*(Tau - 1), (Eta.^2 - 1).*(Xi/4 + 1/4);...
                                (Xi.*(Eta + 1).*(Tau - 1))/2, (Xi.^2/4 - 1/4).*(Tau - 1), (Xi.^2/4 - 1/4).*(Eta + 1);...
                                -((Eta.^2 - 1).*(Tau - 1))/4, -2*Eta.*(Xi/4 - 1/4).*(Tau - 1), -(Eta.^2 - 1).*(Xi/4 - 1/4)];
                            
                        end
                        
                end
            case 'Hermite'
                switch Degree
                    case 3
                        H1 = @(s)  1/4*(2 - 3*s + s.^3);
                        M1 = @(s)  1/4*(1 - s - s.^2 + s.^3);
                        H2 = @(s)  1/4*(2 + 3*s - s.^3);
                        M2 = @(s)  1/4*(-1 - s + s.^2 + s.^3);
                        
                        Kernel_X = [H1(X); M1(X); H2(X); M2(X)];
                        Kernel_Y = [H1(Y); M1(Y); H2(Y); M2(Y)];
                        Kernel_Z = [H1(Z); M1(Z); H2(Z); M2(Z)];
                        
                        Counter = 0;
                        N = zeros(Degree^3,numel(X));
                        AuxIdX = zeros(3,Degree^3);
                        for k=1:Degree+1
                            for i=1:Degree+1
                                for j=1:Degree+1
                                    Counter = Counter + 1;
                                    if i==2 || i == 4
                                        AuxIdX(1,Counter) = 1;
                                    end
                                    if j==2 || j == 4
                                        AuxIdX(2,Counter) = 1;
                                    end
                                    if k==2 || k == 4
                                        AuxIdX(3,Counter) = 1;
                                    end
                                    N(Counter,:) = Kernel_X(i,:).*Kernel_Y(j,:).*Kernel_Z(k,:);
                                end
                            end
                        end
                        IdX = find(AuxIdX(1,:));
                        IdX(2,:) = find(AuxIdX(2,:));
                        IdX(3,:) = find(AuxIdX(3,:));
                        
%                         IdX = [3:4:64 4:4:64;...
%                             2:2:64;...
%                             5:8:64 6:8:64 7:8:64 8:8:64];
%                         N=[...
%                             H1(X).*H1(Y).*H1(Z);...
%                             H1(X).*M1(Y).*H1(Z);...
%                             M1(X).*H1(Y).*H1(Z);...
%                             M1(X).*M1(Y).*H1(Z);...
%                             H1(X).*H1(Y).*M1(Z);...
%                             H1(X).*M1(Y).*M1(Z);...
%                             M1(X).*H1(Y).*M1(Z);...
%                             M1(X).*M1(Y).*M1(Z);...
%                             
%                             H2(X).*H1(Y).*H1(Z);...
%                             H2(X).*M1(Y).*H1(Z);...
%                             M2(X).*H1(Y).*H1(Z);...
%                             M2(X).*M1(Y).*H1(Z);...
%                             H2(X).*H1(Y).*M1(Z);...
%                             H2(X).*M1(Y).*M1(Z);...
%                             M2(X).*H1(Y).*M1(Z);...
%                             M2(X).*M1(Y).*M1(Z);...
%                             
%                             H2(X).*H2(Y).*H1(Z);...
%                             H2(X).*M2(Y).*H1(Z);...
%                             M2(X).*H2(Y).*H1(Z);...
%                             M2(X).*M2(Y).*H1(Z);...
%                             H2(X).*H2(Y).*M1(Z);...
%                             H2(X).*M2(Y).*M1(Z);...
%                             M2(X).*H2(Y).*M1(Z);...
%                             M2(X).*M2(Y).*M1(Z);...
%                             
%                             H1(X).*H2(Y).*H1(Z);...
%                             H1(X).*M2(Y).*H1(Z);...
%                             M1(X).*H2(Y).*H1(Z);...
%                             M1(X).*M2(Y).*H1(Z);...
%                             H1(X).*H2(Y).*M1(Z);...
%                             H1(X).*M2(Y).*M1(Z);...
%                             M1(X).*H2(Y).*M1(Z);...
%                             M1(X).*M2(Y).*M1(Z);...
%                             
%                             H1(X).*H1(Y).*H2(Z);...
%                             H1(X).*M1(Y).*H2(Z);...
%                             M1(X).*H1(Y).*H2(Z);...
%                             M1(X).*M1(Y).*H2(Z);...
%                             H1(X).*H1(Y).*M2(Z);...
%                             H1(X).*M1(Y).*M2(Z);...
%                             M1(X).*H1(Y).*M2(Z);...
%                             M1(X).*M1(Y).*M2(Z);...
%                             
%                             H2(X).*H1(Y).*H2(Z);...
%                             H2(X).*M1(Y).*H2(Z);...
%                             M2(X).*H1(Y).*H2(Z);...
%                             M2(X).*M1(Y).*H2(Z);...
%                             H2(X).*H1(Y).*M2(Z);...
%                             H2(X).*M1(Y).*M2(Z);...
%                             M2(X).*H1(Y).*M2(Z);...
%                             M2(X).*M1(Y).*M2(Z);...
%                             
%                             H2(X).*H2(Y).*H2(Z);...
%                             H2(X).*M2(Y).*H2(Z);...
%                             M2(X).*H2(Y).*H2(Z);...
%                             M2(X).*M2(Y).*H2(Z);...
%                             H2(X).*H2(Y).*M2(Z);...
%                             H2(X).*M2(Y).*M2(Z);...
%                             M2(X).*H2(Y).*M2(Z);...
%                             M2(X).*M2(Y).*M2(Z);...
%                             
%                             H1(X).*H2(Y).*H2(Z);...
%                             H1(X).*M2(Y).*H2(Z);...
%                             M1(X).*H2(Y).*H2(Z);...
%                             M1(X).*M2(Y).*H2(Z);...
%                             H1(X).*H2(Y).*M2(Z);...
%                             H1(X).*M2(Y).*M2(Z);...
%                             M1(X).*H2(Y).*M2(Z);...
%                             M1(X).*M2(Y).*M2(Z)];
                        
                        if CaldN==0
                            dN=0;
                        elseif CaldN>=1
                            dH1 = @(s)  1/4*(-3 + 3*s.^2);
                            dM1 = @(s)  1/4*( -1 -2*s + 3*s^2 );
                            dH2 = @(s)  1/4*(3 - 3*s.^2);
                            dM2 = @(s)  1/4*(-1 + 2*s + 3*s.^2);
                            
                            Kernel_dX = [dH1(X); dM1(X); dH2(X); dM2(X)];
                            Kernel_dY = [dH1(Y); dM1(Y); dH2(Y); dM2(Y)];
                            Kernel_dZ = [dH1(Z); dM1(Z); dH2(Z); dM2(Z)];
                            
                            Counter = 0;
                            dN = zeros(Degree^3,3*numel(X));
                            
                            for i=1:Degree+1
                                for j=1:Degree+1
                                    for k=1:Degree+1
                                        Counter = Counter + 1;
                                        dN(Counter,:) = [Kernel_dX(i,:).*Kernel_Y(j,:).*Kernel_Z(k,:),...
                                            Kernel_X(i,:).*Kernel_dY(j,:).*Kernel_Z(k,:),...
                                            Kernel_X(i,:).*Kernel_Y(j,:).*Kernel_dZ(k,:)];
                                    end
                                end
                            end
                            
%                             dN = [...
%                                 dH1(X).*H1(Y).*H1(Z), H1(X).*dH1(Y).*H1(Z), H1(X).*H1(Y).*dH1(Z);...
%                                 dH1(X).*M1(Y).*H1(Z), H1(X).*dM1(Y).*H1(Z), H1(X).*M1(Y).*dH1(Z);...
%                                 dM1(X).*H1(Y).*H1(Z), M1(X).*dH1(Y).*H1(Z), M1(X).*H1(Y).*dH1(Z);...
%                                 dM1(X).*M1(Y).*H1(Z), M1(X).*dM1(Y).*H1(Z), M1(X).*M1(Y).*dH1(Z);...
%                                 dH1(X).*H1(Y).*M1(Z), H1(X).*dH1(Y).*M1(Z), H1(X).*H1(Y).*dM1(Z);...
%                                 dH1(X).*M1(Y).*M1(Z), H1(X).*dM1(Y).*M1(Z), H1(X).*M1(Y).*dM1(Z);...
%                                 dM1(X).*H1(Y).*M1(Z), M1(X).*dH1(Y).*M1(Z), M1(X).*H1(Y).*dM1(Z);...
%                                 dM1(X).*M1(Y).*M1(Z), M1(X).*dM1(Y).*M1(Z), M1(X).*M1(Y).*dM1(Z);...
%                                 
%                                 dH2(X).*H1(Y).*H1(Z), H2(X).*dH1(Y).*H1(Z), H2(X).*H1(Y).*dH1(Z);...
%                                 dH2(X).*M1(Y).*H1(Z), H2(X).*dM1(Y).*H1(Z), H2(X).*M1(Y).*dH1(Z);...
%                                 dM2(X).*H1(Y).*H1(Z), M2(X).*dH1(Y).*H1(Z), M2(X).*H1(Y).*dH1(Z);...
%                                 dM2(X).*M1(Y).*H1(Z), M2(X).*dM1(Y).*H1(Z), M2(X).*M1(Y).*dH1(Z);...
%                                 dH2(X).*H1(Y).*M1(Z), H2(X).*dH1(Y).*M1(Z), H2(X).*H1(Y).*dM1(Z);...
%                                 dH2(X).*M1(Y).*M1(Z), H2(X).*dM1(Y).*M1(Z), H2(X).*M1(Y).*dM1(Z);...
%                                 dM2(X).*H1(Y).*M1(Z), M2(X).*dH1(Y).*M1(Z), M2(X).*H1(Y).*dM1(Z);...
%                                 dM2(X).*M1(Y).*M1(Z), M2(X).*dM1(Y).*M1(Z), M2(X).*M1(Y).*dM1(Z);...
%                                 
%                                 dH2(X).*H2(Y).*H1(Z), H2(X).*dH2(Y).*H1(Z), H2(X).*H2(Y).*dH1(Z);...
%                                 dH2(X).*M2(Y).*H1(Z), H2(X).*dM2(Y).*H1(Z), H2(X).*M2(Y).*dH1(Z);...
%                                 dM2(X).*H2(Y).*H1(Z), M2(X).*dH2(Y).*H1(Z), M2(X).*H2(Y).*dH1(Z);...
%                                 dM2(X).*M2(Y).*H1(Z), M2(X).*dM2(Y).*H1(Z), M2(X).*M2(Y).*dH1(Z);...
%                                 dH2(X).*H2(Y).*M1(Z), H2(X).*dH2(Y).*M1(Z), H2(X).*H2(Y).*dM1(Z);...
%                                 dH2(X).*M2(Y).*M1(Z), H2(X).*dM2(Y).*M1(Z), H2(X).*M2(Y).*dM1(Z);...
%                                 dM2(X).*H2(Y).*M1(Z), M2(X).*dH2(Y).*M1(Z), M2(X).*H2(Y).*dM1(Z);...
%                                 dM2(X).*M2(Y).*M1(Z), M2(X).*dM2(Y).*M1(Z), M2(X).*M2(Y).*dM1(Z);...
%                                 
%                                 dH1(X).*H2(Y).*H1(Z), H1(X).*dH2(Y).*H1(Z), H1(X).*H2(Y).*dH1(Z);...
%                                 dH1(X).*M2(Y).*H1(Z), H1(X).*dM2(Y).*H1(Z), H1(X).*M2(Y).*dH1(Z);...
%                                 dM1(X).*H2(Y).*H1(Z), M1(X).*dH2(Y).*H1(Z), M1(X).*H2(Y).*dH1(Z);...
%                                 dM1(X).*M2(Y).*H1(Z), M1(X).*dM2(Y).*H1(Z), M1(X).*M2(Y).*dH1(Z);...
%                                 dH1(X).*H2(Y).*M1(Z), H1(X).*dH2(Y).*M1(Z), H1(X).*H2(Y).*dM1(Z);...
%                                 dH1(X).*M2(Y).*M1(Z), H1(X).*dM2(Y).*M1(Z), H1(X).*M2(Y).*dM1(Z);...
%                                 dM1(X).*H2(Y).*M1(Z), M1(X).*dH2(Y).*M1(Z), M1(X).*H2(Y).*dM1(Z);...
%                                 dM1(X).*M2(Y).*M1(Z), M1(X).*dM2(Y).*M1(Z), M1(X).*M2(Y).*dM1(Z);...
%                                 
%                                 dH1(X).*H1(Y).*H2(Z), H1(X).*dH1(Y).*H2(Z), H1(X).*H1(Y).*dH2(Z);...
%                                 dH1(X).*M1(Y).*H2(Z), H1(X).*dM1(Y).*H2(Z), H1(X).*M1(Y).*dH2(Z);...
%                                 dM1(X).*H1(Y).*H2(Z), M1(X).*dH1(Y).*H2(Z), M1(X).*H1(Y).*dH2(Z);...
%                                 dM1(X).*M1(Y).*H2(Z), M1(X).*dM1(Y).*H2(Z), M1(X).*M1(Y).*dH2(Z);...
%                                 dH1(X).*H1(Y).*M2(Z), H1(X).*dH1(Y).*M2(Z), H1(X).*H1(Y).*dM2(Z);...
%                                 dH1(X).*M1(Y).*M2(Z), H1(X).*dM1(Y).*M2(Z), H1(X).*M1(Y).*dM2(Z);...
%                                 dM1(X).*H1(Y).*M2(Z), M1(X).*dH1(Y).*M2(Z), M1(X).*H1(Y).*dM2(Z);...
%                                 dM1(X).*M1(Y).*M2(Z), M1(X).*dM1(Y).*M2(Z), M1(X).*M1(Y).*dM2(Z);...
%                                 
%                                 dH2(X).*H1(Y).*H2(Z), H2(X).*dH1(Y).*H2(Z), H2(X).*H1(Y).*dH2(Z);...
%                                 dH2(X).*M1(Y).*H2(Z), H2(X).*dM1(Y).*H2(Z), H2(X).*M1(Y).*dH2(Z);...
%                                 dM2(X).*H1(Y).*H2(Z), M2(X).*dH1(Y).*H2(Z), M2(X).*H1(Y).*dH2(Z);...
%                                 dM2(X).*M1(Y).*H2(Z), M2(X).*dM1(Y).*H2(Z), M2(X).*M1(Y).*dH2(Z);...
%                                 dH2(X).*H1(Y).*M2(Z), H2(X).*dH1(Y).*M2(Z), H2(X).*H1(Y).*dM2(Z);...
%                                 dH2(X).*M1(Y).*M2(Z), H2(X).*dM1(Y).*M2(Z), H2(X).*M1(Y).*dM2(Z);...
%                                 dM2(X).*H1(Y).*M2(Z), M2(X).*dH1(Y).*M2(Z), M2(X).*H1(Y).*dM2(Z);...
%                                 dM2(X).*M1(Y).*M2(Z), M2(X).*dM1(Y).*M2(Z), M2(X).*M1(Y).*dM2(Z);...
%                                 
%                                 dH2(X).*H2(Y).*H2(Z), H2(X).*dH2(Y).*H2(Z), H2(X).*H2(Y).*dH2(Z);...
%                                 dH2(X).*M2(Y).*H2(Z), H2(X).*dM2(Y).*H2(Z), H2(X).*M2(Y).*dH2(Z);...
%                                 dM2(X).*H2(Y).*H2(Z), M2(X).*dH2(Y).*H2(Z), M2(X).*H2(Y).*dH2(Z);...
%                                 dM2(X).*M2(Y).*H2(Z), M2(X).*dM2(Y).*H2(Z), M2(X).*M2(Y).*dH2(Z);...
%                                 dH2(X).*H2(Y).*M2(Z), H2(X).*dH2(Y).*M2(Z), H2(X).*H2(Y).*dM2(Z);...
%                                 dH2(X).*M2(Y).*M2(Z), H2(X).*dM2(Y).*M2(Z), H2(X).*M2(Y).*dM2(Z);...
%                                 dM2(X).*H2(Y).*M2(Z), M2(X).*dH2(Y).*M2(Z), M2(X).*H2(Y).*dM2(Z);...
%                                 dM2(X).*M2(Y).*M2(Z), M2(X).*dM2(Y).*M2(Z), M2(X).*M2(Y).*dM2(Z);...
%                                 
%                                 dH1(X).*H2(Y).*H2(Z), H1(X).*dH2(Y).*H2(Z), H1(X).*H2(Y).*dH2(Z);...
%                                 dH1(X).*M2(Y).*H2(Z), H1(X).*dM2(Y).*H2(Z), H1(X).*M2(Y).*dH2(Z);...
%                                 dM1(X).*H2(Y).*H2(Z), M1(X).*dH2(Y).*H2(Z), M1(X).*H2(Y).*dH2(Z);...
%                                 dM1(X).*M2(Y).*H2(Z), M1(X).*dM2(Y).*H2(Z), M1(X).*M2(Y).*dH2(Z);...
%                                 dH1(X).*H2(Y).*M2(Z), H1(X).*dH2(Y).*M2(Z), H1(X).*H2(Y).*dM2(Z);...
%                                 dH1(X).*M2(Y).*M2(Z), H1(X).*dM2(Y).*M2(Z), H1(X).*M2(Y).*dM2(Z);...
%                                 dM1(X).*H2(Y).*M2(Z), M1(X).*dH2(Y).*M2(Z), M1(X).*H2(Y).*dM2(Z);...
%                                 dM1(X).*M2(Y).*M2(Z), M1(X).*dM2(Y).*M2(Z), M1(X).*M2(Y).*dM2(Z)];
                        end
                    case 4 % Paper Int. J. Numer. Meth. Engng 2017; 109:936–964 -> DOI: 10.1002/nme.5308
                        H1 = @(s)  1/4*(2 - 3*s + s.^3);
                        M1 = @(s)  1/4*(1 - s - s.^2 + s.^3);
                        H2 = @(s)  1/4*(2 + 3*s - s.^3);
                        M2 = @(s)  1/4*(-1 - s + s.^2 + s.^3);
                        
                        H5 = @(s)  1/4*(-3 + 6*s.^2 - 3*s.^4);
                        
                        Kernel_X = [H1(X); M1(X); H2(X); M2(X); H5(X)];
                        Kernel_Y = [H1(Y); M1(Y); H2(Y); M2(Y); H5(Y)];
                        Kernel_Z = [H1(Z); M1(Z); H2(Z); M2(Z); H5(Z)];
                        
                        Counter = 0;
                        N = zeros(Degree^3,numel(X));
                        AuxIdX = zeros(3,Degree^3);
                        for i=1:Degree+1
                            for j=1:Degree+1
                                for k=1:Degree+1
                                    if i==2 || i == 4
                                        AuxIdX(1,Counter) = 1;
                                    end
                                    if j==2 || j == 4
                                        AuxIdX(2,Counter) = 1;
                                    end
                                    if k==2 || k == 4
                                        AuxIdX(3,Counter) = 1;
                                    end
                                    Counter = Counter + 1;
                                    N(Counter,:) = Kernel_X(i,:).*Kernel_Y(j,:).*Kernel_Z(k,:);
                                end
                            end
                        end
                        IdX = find(AuxIdX(1,:));
                        IdX(2,:) = find(AuxIdX(2,:));
                        IdX(3,:) = find(AuxIdX(3,:));
                        
                        
                        if CaldN==0
                            dN=0;
                        elseif CaldN>=1
                            dH1 = @(s)  1/4*(-3 + 3*s.^2);
                            dM1 = @(s)  1/4*( -1 -2*s + 3*s^2 );
                            dH2 = @(s)  1/4*(3 - 3*s.^2);
                            dM2 = @(s)  1/4*(-1 + 2*s + 3*s.^2);
                            
                            dH5 = @(s)  1/4*(12*s - 12*s.^3);
                            
                            Kernel_dX = [dH1(X); dM1(X); dH2(X); dM2(X); dH5(X)];
                            Kernel_dY = [dH1(Y); dM1(Y); dH2(Y); dM2(Y); dH5(Y)];
                            Kernel_dZ = [dH1(Z); dM1(Z); dH2(Z); dM2(Z); dH5(Z)];
                            
                            Counter = 0;
                            dN = zeros(Degree^3,3*numel(X));
                            
                            for i=1:Degree+1
                                for j=1:Degree+1
                                    for k=1:Degree+1
                                        Counter = Counter + 1;
                                        dN(Counter,:) = [Kernel_dX(i,:).*Kernel_Y(j,:).*Kernel_Z(k,:),...
                                            Kernel_X(i,:).*Kernel_dY(j,:).*Kernel_Z(k,:),...
                                            Kernel_X(i,:).*Kernel_Y(j,:).*Kernel_dZ(k,:)];
                                    end
                                end
                            end
                            
                        end
                        
                        
                        
                end
                
            otherwise
                error('Not implemented');
        end
end


N = N';

if CaldN ~=0
    dN=dN';
    
    dNdPsi=dN(1:size(Coor,1),:);
    dNdEta=dN(size(Coor,1)+1:2*size(Coor,1),:);
    dNdTau=dN(2*size(Coor,1)+1:end,:);
else
    dNdPsi=[];
    dNdEta=[];
    dNdTau = [];
end

