function [N,dNpsi,dNeta,dNpsipsi,dNpsieta,dNetaeta]=Shapef_2D(Coor,Degree,NSidesElem,CaldN)
% Shape functions and derivatives evaluated at Coor (X=psi, Y=eta)
% Implemented for triangles and quadrilaterals
%
% IMPORTANT: Node numbering. Vertex nodes are numbered before mid-side nodes.

% Input:---------------
%    Coor        = coordinates (X=psi e Y=eta)
%    Degree      = Degree of shape functions
%    NSidesElem  = Number of sides  (3 or 4)
%    CaldN       = flag used to indicate evaluation of dN
%                     0    ==> dN will not be calculated
%                     else ==> dN will be calculated
% Output:-------------
%   N        = Shape functions matrix. Each row corresponds to the values
%              of N at point (x,y)
%   dNpsi    = Idem for derivatives with respect to psi
%   dNeta    = Idem for derivatives with respect to eta
%   dNpsipsi = Idem for 2nd derivatives with respect to psipsi
%   dNpsieta = Idem for 2nd derivatives with respect to psieta
%   dNetaeta = Idem for 2nd derivatives with respect to etaeta


if nargin==3
    CaldN=0;
end



X=Coor(:,1)';
Y=Coor(:,2)';
Zeros = zeros(1,size(Coor,1));
Ones = ones(1,size(Coor,1));

switch NSidesElem
    
    case 3 % TRIANGLES -----------------------------
        switch Degree
            case 1 %Linear Triangles
                N=[...
                    1-X-Y;...
                    X;...
                    Y];
                if CaldN==0
                    dN=0;
                else
                    dN=[...
                        -1+0.*X,-1+0.*X;...
                        +1+0.*X, 0+0.*X;...
                        0+0.*X, 1+0.*X];
                    
                end
                
            case 2 %Quadratic triangles
                N=[...
                    (1-X-Y).*(1-2*X-2*Y);...
                    -X.*(1-2*X);...
                    -Y.*(1-2*Y);...
                    4*X.*(1-X-Y);...
                    4*X.*Y;...
                    4*Y.*(1-X-Y)];
                if CaldN==0
                    dN=0;
                else
                    dN=[...
                        -3+4*X+4*Y , -3+4*X+4*Y;...
                        -1+4*X     ,  0.*X        ;...
                        +0.*X      , -1+4*Y    ;...
                        +4-8*X-4*Y , -4*X      ;...
                        +4*Y       ,  4*X      ;...
                        -4*Y       , +4-4*X-8*Y];
                end
                
            case 3 %Cubic triangles
                N=[...
                    -0.5*(X+Y-1).*(3*X+3*Y-2).*(3*X+3*Y-1);...
                    +0.5*X.*(3*X-1).*(3*X-2);...
                    +0.5*Y.*(3*Y-1).*(3*Y-2);...
                    +4.5*X.*(X+Y-1).*(3*X+3*Y-2);...
                    -4.5*(X+Y-1).*X.*(3*X-1);...
                    +4.5*X.*Y.*(3*X-1);...
                    +4.5*X.*Y.*(3*Y-1);...
                    -4.5*(X+Y-1).*Y.*(3*Y-1);
                    +4.5*(X+Y-1).*Y.*(3*X+3*Y-2);
                    -27*X.*Y.*(X+Y-1)];
                if CaldN==0
                    dN=0;
                else
                    dN=[...
                        -13.5*(X.^2+Y.^2+2*X.*Y)+18*(X+Y)-5.5      , -13.5*(X.^2+Y.^2+2*X.*Y)+18*(X+Y)-5.5;...
                        +13.5*X.^2-9*X+1                           , 0.*X;...
                        +0.*X                                      , +13.5*Y.^2-9*Y+1;...
                        +40.5*X.^2+54*X.*Y-45*X+13.5*Y.^2-22.5*Y+9 , +4.5*X.*(6*X+6*Y-5);...
                        -40.5*X.^2+36*X-27*X.*Y+4.5*Y-4.5          , -4.5*X.*(3*X-1);...
                        +27*X.*Y-4.5*Y                             , +4.5*X.*(3*X-1);...
                        +4.5*Y.*(3*Y-1)                            , +27*X.*Y-4.5*X;...
                        -4.5*Y.*(3*Y-1)                            , -40.5*Y.^2+36*Y-27*X.*Y+4.5*X-4.5;...
                        +4.5*Y.*(6*Y+6*X-5)                        , +40.5*Y.^2+54*X.*Y-45*Y+13.5*X.^2-22.5*X+9;...
                        -27*Y.*(Y+2*X-1)                           , -27*X.*(X+2*Y-1)];
                end
            otherwise %Other Triangles
                disp(['Degree ' num2str(Degree)...
                    ' not implemented for triangles']);
                error('Aborting execution');
        end
    case 4 % QUADRILATERALS --------------------------------
        switch Degree
            case 1  %Linear Quadrilaterals
                N=[...
                    (1-Y).*(1-X);...
                    (1-Y).*(1+X);...
                    (1+Y).*(1+X);...
                    (1+Y).*(1-X)]/4;
                if CaldN==0
                    dN=0;
                else
                    dN=[...
                        (-1+Y), (-1+X);...
                        (+1-Y), (-1-X);...
                        (+1+Y), (+1+X);...
                        (-1-Y), (+1-X)]/4;
                    
                    %                     dN2 = [...
                    %                            Zeros,  Ones , Zeros; ...
                    %                            Zeros, -1*Ones , Zeros; ...
                    %                            Zeros,  Ones , Zeros; ...
                    %                            Zeros, -1*Ones , Zeros]/4;
                end
                
            case 2  %Quadratic Quadrilaterals
                N=[...
                    -(1-Y).*(1-X).*(1+X+Y)/2 ;...
                    -(1-Y).*(1+X).*(1-X+Y)/2 ;...
                    -(1+Y).*(1+X).*(1-X-Y)/2 ;...
                    -(1+Y).*(1-X).*(1+X-Y)/2 ;...
                    +(1-X.^2).*(1-Y)       ;...
                    +(1-Y.^2).*(1+X)       ;...
                    +(1-X.^2).*(1+Y)       ;...
                    +(1-Y.^2).*(1-X)       ]/2;
                if CaldN==0
                    dN=0;
                else
                    dN=[...
                        -(-1+Y).*(Y+2*X)/4  , -(-1+X).*(X+2*Y)/4  ;...
                        -(-1+Y).*(-Y+2*X)/4 , -(1+X).*(X-2*Y)/4   ;...
                        +(Y+1).*(Y+2*X)/4   , +(1+X).*(X+2*Y)/4   ;...
                        -(Y+1).*(Y-2*X)/4   , -(-1+X).*(-X+2*Y)/4 ;...
                        -X.*(1-Y)           , +(-1+X.^2)/2        ;...
                        +(1-Y.^2)/2         , -Y.*(1+X)           ;...
                        -X.*(Y+1)           , +(1-X.^2)/2         ;...
                        +(-1+Y.^2)/2        , -Y.*(1-X)           ];
                    %                     dN2 = [];
                end
            case 3  %Cubic Quadrilaterals
                X2=X.^2;
                X3=X.^3;
                Y2=Y.^2;
                Y3=Y.^3;
                
                X21Y11 = (1-X2).*(1-Y);% the first sub-index means the exponent of the
                X21Y12 = (1-X2).*(1+Y);% variable, and the second is two if the variable
                X11Y21 = (1-Y2).*(1-X);% is addind,and one if it is remaining.
                X12Y21 = (1-Y2).*(1+X);
                
                
                N = [...
                    9/32*(1-X).*(1-Y).*(Y2 + X2 - 10/9);...
                    9/32*(1+X).*(1-Y).*(Y2 + X2 - 10/9);...
                    9/32*(1+X).*(1+Y).*(Y2 + X2 - 10/9);...
                    9/32*(1-X).*(1+Y).*(Y2 + X2 - 10/9);...
                    9/32*X21Y11.*(1-3*X);...
                    9/32*X21Y11.*(1+3*X);...
                    9/32*X12Y21.*(1-3*Y);...
                    9/32*X12Y21.*(1+3*Y);...
                    9/32*X21Y12.*(1+3*X);...
                    9/32*X21Y12.*(1-3*X);...
                    9/32*X11Y21.*(1+3*Y);...
                    9/32*X11Y21.*(1-3*Y)               ];
                
                if CaldN==0
                    dN=0;
                else
                    X22X11Y = (27*X2 - 18*X - 10).*Y;
                    X22X12Y = (27*X2 + 18*X - 10).*Y;
                    X11Y2 = (27*X - 27).*Y2;
                    X12Y2 = (27*X + 27).*Y2;
                    X11Y = (18*X - 18).*Y;
                    X12Y = (18*X + 18).*Y;
                    
                    dN = [...
                        
                    1/32*( 9*Y3 - 9*Y2 + X22X11Y - 27*X2 + 18*X + 10) ,...       %dN1/dX
                    1/32*(X11Y2 - X11Y + 9*X3 - 9*X2 - 10*X + 10);...            %dN1/dY
                    
                    -1/32*( 9*Y3 - 9*Y2 + X22X12Y - 27*X2 - 18*X + 10) ,...       %dN2/dX
                    -1/32*(X12Y2 - X12Y + 9*X3 + 9*X2 - 10*X - 10);...            %dN2/dY
                    
                    1/32*( 9*Y3 + 9*Y2 + X22X12Y + 27*X2 + 18*X - 10) ,...       %dN3/dX
                    1/32*(X12Y2 + X12Y + 9*X3 + 9*X2 - 10*X - 10);...            %dN3/dY
                    
                    -1/32*( 9*Y3 + 9*Y2 + X22X11Y + 27*X2 - 18*X - 10) ,...       %dN4/dX
                    -1/32*(X11Y2 + X11Y + 9*X3 - 9*X2 - 10*X + 10);...            %dN4/dY
                    
                    -1/32*((81*X2 - 18*X -27).*Y - 81*X2 + 18*X + 27),...         %dN5/dX
                    -1/32*((27*X3 - 9*X2 - 27*X + 9));...                         %dN5/dY
                    
                    1/32*((81*X2 + 18*X -27).*Y - 81*X2 - 18*X + 27),...         %dN6/dX
                    1/32*((27*X3 + 9*X2 - 27*X - 9));...                         %dN6/dY
                    
                    1/32*(27*Y3 - 9*Y2 - 27*Y + 9),...                           %dN7/dX
                    1/32*((81*X + 81).*Y2 - X12Y - 27*X -27);...                 %dN7/dX
                    
                    -1/32*(27*Y3 + 9*Y2 - 27*Y - 9),...                           %dN8/dX
                    -1/32*((81*X + 81).*Y2 + X12Y - 27*X -27);...                 %dN8/dX
                    
                    -1/32*((81*X2 + 18*X -27).*Y + 81*X2 + 18*X - 27),...         %dN9/dX
                    -1/32*((27*X3 + 9*X2 - 27*X - 9));...                         %dN9/dY
                    
                    1/32*((81*X2 - 18*X -27).*Y + 81*X2 - 18*X - 27),...         %dN10/dX
                    1/32*((27*X3 - 9*X2 - 27*X + 9));...                         %dN10/dY
                    
                    1/32*(27*Y3 + 9*Y2 - 27*Y - 9),...                           %dN11/dX
                    1/32*((81*X - 81).*Y2 + X11Y - 27*X +27);...                 %dN11/dX
                    
                    -1/32*(27*Y3 - 9*Y2 - 27*Y + 9),...                           %dN12/dX
                    -1/32*((81*X - 81).*Y2 - X11Y - 27*X +27)];                   %dN12/dX
                
                
                end
                
            case 4  %4th Quadrilaterals
                X2=X.^2;
                X3=X.^3;
                Y2=Y.^2;
                Y3=Y.^3;
                
                
                N = [...
                    -1/12 * (-1 + Y) .* (-1 + X).*(4*X3 - 3*X.*Y -4*X + 4*Y3 - 4*Y);
                    -1/12 * (-1 + Y) .* (1 + X).*(4*X3 - 3*X.*Y -4*X - 4*Y3 + 4*Y);
                     1/12 * (1 + Y) .* (1 + X).*(4*X3 + 3*X.*Y -4*X + 4*Y3 - 4*Y);
                     1/12 * (1 + Y) .* (-1 + X).*(4*X3 + 3*X.*Y -4*X - 4*Y3 + 4*Y);
                     2/3*X.*(-1+X).*(2*X-1).*(1+X).*(-1+Y);
                     -2/3*Y.*(-1+Y).*(2*Y-1).*(1+Y).*(1+X);
                     -2/3*X.*(-1+X).*(2*X+1).*(1+X).*(1+Y);
                     2/3*Y.*(-1+Y).*(2*Y+1).*(1+Y).*(-1+X);
                     -1/2*(-1+Y).*(-1+X).*(1+X).*(Y+4*X2); 
                     -1/2*(-1+Y).*(1+Y).*(1+X).*(X-4*Y2);
                      1/2*(1+Y).*(-1+X).*(1+X).*(-Y+4*X2);
                     -1/2*(-1+Y).*(1+Y).*(-1+X).*(X+4*Y2);
                      2/3*X.*(-1+X).*(2*X+1).*(1+X).*(-1+Y);
                     -2/3*Y.*(-1+Y).*(2*Y+1).*(1+Y).*(1+X);
                     -2/3*X.*(-1+X).*(2*X-1).*(1+X).*(1+Y);
                      2/3*Y.*(-1+Y).*(2*Y-1).*(1+Y).*(-1+X);
                      (1-X2).*(1-Y2)                    ];
                
                if CaldN==0
                    dN=0;
                else
                    dNdX = [(-1/12).*((-1)+X).*((-4)+12.*X2+(-3).*Y).*((-1)+Y)+(-1/12).*((-1)+Y).*((-4).*X+4.*X3+(-4).*Y+(-3).*X.*Y+4.*Y3);
                        (-1/12).*(1+X).*((-4)+12.*X2+(-3).*Y).*((-1)+Y)+(-1/12).*((-1)+Y).*((-4).*X+4.*X3+4.*Y+(-3).*X.*Y+(-4).*Y3);
                        (1/12).*(1+X).*(1+Y).*((-4)+12.*X2+3.*Y)+(1/12).*(1+Y).*((-4).*X+4.*X3+(-4).*Y+3.*X.*Y+4.*Y3);
                        (1/12).*((-1)+X).*(1+Y).*((-4)+12.*X2+3.*Y)+(1/12).*(1+Y).*((-4).*X+4.*X3+4.*Y+3.*X.*Y+(-4).*Y3);
                        (4/3).*((-1)+X).*X.*(1+X).*((-1)+Y)+(2/3).*((-1)+X).*X.*((-1)+2.*X).*((-1)+Y)+(2/3).*((-1)+X).*(1+X).*((-1)+2.*X).*((-1)+Y)+(2/3).*X.*(1+X).*((-1)+2.*X).*((-1)+Y);
                        (-2/3).*((-1)+Y).*Y.*(1+Y).*((-1)+2.*Y);
                        (-4/3).*((-1)+X).*X.*(1+X).*(1+Y)+(-2/3).*((-1)+X).*X.*(1+2.*X).*(1+Y)+(-2/3).*((-1)+X).*(1+X).*(1+2.*X).*(1+Y)+(-2/3).*X.*(1+X).*(1+2.*X).*(1+Y);
                        (2/3).*((-1)+Y).*Y.*(1+Y).*(1+2.*Y);
                        (-4).*((-1)+X).*X.*(1+X).*((-1)+Y)+(-1/2).*((-1)+X).*((-1)+Y).*(4.*X2+Y)+(-1/2).*(1+X).*((-1)+Y).*(4.*X2+Y);
                        (-1/2).*(1+X).*((-1)+Y).*(1+Y)+(-1/2).*((-1)+Y).*(1+Y).*(X+(-4).*Y2);
                        4.*((-1)+X).*X.*(1+X).*(1+Y)+(1/2).*((-1)+X).*(4.*X2+(-1).*Y).*(1+Y)+(1/2).*(1+X).*(4.*X2+(-1).*Y).*(1+Y);
                        (-1/2).*((-1)+X).*((-1)+Y).*(1+Y)+(-1/2).*((-1)+Y).*(1+Y).*(X+4.*Y2);
                        (4/3).*((-1)+X).*X.*(1+X).*((-1)+Y)+(2/3).*((-1)+X).*X.*(1+2.*X).*((-1)+Y)+(2/3).*((-1)+X).*(1+X).*(1+2.*X).*((-1)+Y)+(2/3).*X.*(1+X).*(1+2.*X).*((-1)+Y);
                        (-2/3).*((-1)+Y).*Y.*(1+Y).*(1+2.*Y);
                        (-4/3).*((-1)+X).*X.*(1+X).*(1+Y)+(-2/3).*((-1)+X).*X.*((-1)+2.*X).*(1+Y)+(-2/3).*((-1)+X).*(1+X).*((-1)+2.*X).*(1+Y)+(-2/3).*X.*(1+X).*((-1)+2.*X).*(1+Y);
                        (2/3).*((-1)+Y).*Y.*(1+Y).*((-1)+2.*Y);
                        (-2).*X.*(1+(-1).*Y2)];
                    
                    dNdY = [(-1/12).*((-1)+X).*((-1)+Y).*((-4)+(-3).*X+12.*Y2)+(-1/12).*((-1)+X).*((-4).*X+4.*X3+(-4).*Y+(-3).*X.*Y+4.*Y3);
                        (-1/12).*(1+X).*((-1)+Y).*(4+(-3).*X+(-12).*Y2)+(-1/12).*(1+X).*((-4).*X+4.*X3+4.*Y+(-3).*X.*Y+(-4).*Y3);
                        (1/12).*(1+X).*(1+Y).*((-4)+3.*X+12.*Y2)+(1/12).*(1+X).*((-4).*X+4.*X3+(-4).*Y+3.*X.*Y+4.*Y3);
                        (1/12).*((-1)+X).*(1+Y).*(4+3.*X+(-12).*Y2)+(1/12).*((-1)+X).*((-4).*X+4.*X3+4.*Y+3.*X.*Y+(-4).*Y3);
                        (2/3).*((-1)+X).*X.*(1+X).*((-1)+2.*X);
                        (-4/3).*(1+X).*((-1)+Y).*Y.*(1+Y)+(-2/3).*(1+X).*((-1)+Y).*Y.*((-1)+2.*Y)+(-2/3).*(1+X).*((-1)+Y).*(1+Y).*((-1)+2.*Y)+(-2/3).*(1+X).*Y.*(1+Y).*((-1)+2.*Y);
                        (-2/3).*((-1)+X).*X.*(1+X).*(1+2.*X);
                        (4/3).*((-1)+X).*((-1)+Y).*Y.*(1+Y)+(2/3).*((-1)+X).*((-1)+Y).*Y.*(1+2.*Y)+(2/3).*((-1)+X).*((-1)+Y).*(1+Y).*(1+2.*Y)+(2/3).*((-1)+X).*Y.*(1+Y).*(1+2.*Y);
                        (-1/2).*((-1)+X).*(1+X).*((-1)+Y)+(-1/2).*((-1)+X).*(1+X).*(4.*X2+Y);
                        4.*(1+X).*((-1)+Y).*Y.*(1+Y)+(-1/2).*(1+X).*((-1)+Y).*(X+(-4).*Y2)+(-1/2).*(1+X).*(1+Y).*(X+(-4).*Y2);
                        (1/2).*((-1)+X).*(1+X).*(4.*X2+(-1).*Y)+(-1/2).*((-1)+X).*(1+X).*(1+Y);
                        (-4).*((-1)+X).*((-1)+Y).*Y.*(1+Y)+(-1/2).*((-1)+X).*((-1)+Y).*(X+4.*Y2)+(-1/2).*((-1)+X).*(1+Y).*(X+4.*Y2);
                        (2/3).*((-1)+X).*X.*(1+X).*(1+2.*X);
                        (-4/3).*(1+X).*((-1)+Y).*Y.*(1+Y)+(-2/3).*(1+X).*((-1)+Y).*Y.*(1+2.*Y)+(-2/3).*(1+X).*((-1)+Y).*(1+Y).*(1+2.*Y)+(-2/3).*(1+X).*Y.*(1+Y).*(1+2.*Y);
                        (-2/3).*((-1)+X).*X.*(1+X).*((-1)+2.*X);
                        (4/3).*((-1)+X).*((-1)+Y).*Y.*(1+Y)+(2/3).*((-1)+X).*((-1)+Y).*Y.*((-1)+2.*Y)+(2/3).*((-1)+X).*((-1)+Y).*(1+Y).*((-1)+2.*Y)+(2/3).*((-1)+X).*Y.*(1+Y).*((-1)+2.*Y);
                        (-2).*(1+(-1).*X2).*Y];
                    
                    
                    dN = [dNdX,dNdY];
                   
                end
            case 'Hermite'
                H1 = @(s) 0.25*(2*ones(size(s)) - 3*s + s.^3);
                M1 = @(s) 0.25*(1*ones(size(s)) - s -s.^2 + s.^3);
                H2 = @(s) 0.25*(2*ones(size(s)) + 3*s - s.^3);
                M2 = @(s) 0.25*(-1*ones(size(s)) - s + s.^2 + s.^3);
                    N=[...
                    H1(X).*H1(Y);...
                    H1(X).*M1(Y);...
                    M1(X).*H1(Y);...
                    M1(X).*M1(Y);...
                    
                    H2(X).*H1(Y);...
                    H2(X).*M1(Y);...
                    M2(X).*H1(Y);...
                    M2(X).*M1(Y);...
                    
                    H2(X).*H2(Y);...
                    H2(X).*M2(Y);...
                    M2(X).*H2(Y);...
                    M2(X).*M2(Y);...
                    
                    H1(X).*H2(Y);...
                    H1(X).*M2(Y);...
                    M1(X).*H2(Y);...
                    M1(X).*M2(Y)];
                
                if CaldN==0
                    dN=0;
                elseif CaldN>=1
                    dH1 = @(s) 0.25*(-3*ones(size(s)) + 3*s.^2);
                    dM1 = @(s) 0.25*(-1*ones(size(s)) -2*s + 3*s.^2);
                    dH2 = @(s) 0.25*(3*ones(size(s)) - 3*s.^2);
                    dM2 = @(s) 0.25*(-1*ones(size(s)) +2*s + 3*s.^2);
                    
                    dN = [...
                        dH1(X).*H1(Y) , H1(X).*dH1(Y);...
                        dH1(X).*M1(Y) , H1(X).*dM1(Y);...
                        dM1(X).*H1(Y) , M1(X).*dH1(Y);...
                        dM1(X).*M1(Y) , M1(X).*dM1(Y);...
                        
                        dH2(X).*H1(Y) , H2(X).*dH1(Y);...
                        dH2(X).*M1(Y) , H2(X).*dM1(Y);...
                        dM2(X).*H1(Y) , M2(X).*dH1(Y);...
                        dM2(X).*M1(Y) , M2(X).*dM1(Y);...
                        
                        dH2(X).*H2(Y) , H2(X).*dH2(Y);...
                        dH2(X).*M2(Y) , H2(X).*dM2(Y);...
                        dM2(X).*H2(Y) , M2(X).*dH2(Y);...
                        dM2(X).*M2(Y) , M2(X).*dM2(Y);...
                        
                        dH1(X).*H2(Y) , H1(X).*dH2(Y);...
                        dH1(X).*M2(Y) , H1(X).*dM2(Y);...
                        dM1(X).*H2(Y) , M1(X).*dH2(Y);...
                        dM1(X).*M2(Y) , M1(X).*dM2(Y)];
                    if CaldN==2
                        ddH1 = @(s) 0.25*(6*s);
                        ddM1 = @(s) 0.25*(-2*ones(size(s)) +6*s);
                        ddH2 = @(s) 0.25*(- 6*s);
                        ddM2 = @(s) 0.25*(2*ones(size(s)) +6*s);
                        
                        dN2 = [...
                            ddH1(X).*H1(Y) , dH1(X).*dH1(Y) , H1(X).*ddH1(Y);...
                            ddH1(X).*M1(Y) , dH1(X).*dM1(Y) , H1(X).*ddM1(Y);...
                            ddM1(X).*H1(Y) , dM1(X).*dH1(Y) , M1(X).*ddH1(Y);...
                            ddM1(X).*M1(Y) , dM1(X).*dM1(Y) , M1(X).*ddM1(Y);...
                            
                            ddH2(X).*H1(Y) , dH2(X).*dH1(Y) , H2(X).*ddH1(Y);...
                            ddH2(X).*M1(Y) , dH2(X).*dM1(Y) , H2(X).*ddM1(Y);...
                            ddM2(X).*H1(Y) , dM2(X).*dH1(Y) , M2(X).*ddH1(Y);...
                            ddM2(X).*M1(Y) , dM2(X).*dM1(Y) , M2(X).*ddM1(Y);...
                            
                            ddH2(X).*H2(Y) , dH2(X).*dH2(Y) , H2(X).*ddH2(Y);...
                            ddH2(X).*M2(Y) , dH2(X).*dM2(Y) , H2(X).*ddM2(Y);...
                            ddM2(X).*H2(Y) , dM2(X).*dH2(Y) , M2(X).*ddH2(Y);...
                            ddM2(X).*M2(Y) , dM2(X).*dM2(Y) , M2(X).*ddM2(Y);...
                            
                            ddH1(X).*H2(Y) , dH1(X).*dH2(Y) , H1(X).*ddH2(Y);...
                            ddH1(X).*M2(Y) , dH1(X).*dM2(Y) , H1(X).*ddM2(Y);...
                            ddM1(X).*H2(Y) , dM1(X).*dH2(Y) , M1(X).*ddH2(Y);...
                            ddM1(X).*M2(Y) , dM1(X).*dM2(Y) , M1(X).*ddM2(Y)];
                       
                    end
                end    
            
            otherwise %Other Quadrilaterals
                
                disp(['Degree  ' num2str(Degree)...
                    ' not implemented for quadrilaterals']);
                error('Aborting eXecution');
        end
    otherwise
        disp (['An element with ',num2str(NSidesElem),...
            ' sides has been specified']);
        error('Aborting eXecution');
        
end

N=N';

if CaldN == 1
    dN=dN';
    %     dN2=dN2';
    dNpsi=dN(1:size(Coor,1),:);
    dNeta=dN(size(Coor,1)+1:end,:);
    dNpsipsi = [];
    dNpsieta = [];
    dNetaeta = [];
elseif CaldN == 2
    dN=dN';
    dN2=dN2';
    dNpsi=dN(1:size(Coor,1),:);
    dNeta=dN(size(Coor,1)+1:end,:);
    dNpsipsi = dN2(1:size(Coor,1),:);
    dNpsieta = dN2(size(Coor,1)+1:2*size(Coor,1),:);
    dNetaeta = dN2(2*size(Coor,1)+1:3*size(Coor,1),:);
else
    dNpsi=[];
    dNeta=[];
    dNpsipsi = [];
    dNpsieta = [];
    dNetaeta = [];
end

return;